tinyMCE.addI18n('de.txpimage_dlg',{
    tab_general:"Allgemein",
    tab_appearance:"Darstellung",
    tab_advanced:"Erweitert",
    general:"Allgemein",
    title:"Titel",
    preview:"Vorschau",
    constrain_proportions:"Proportionen einschränken",
    langdir:"Sprachrichtung",
    langcode:"Sprachcode",
    long_desc:"Link zur langen Beschreibung",
    style:"Stil",
    classes:"Klassen",
    ltr:"Von links nach rechts",
    rtl:"Von rechts nach links",
    id:"ID",
    map:"Image map",
    swap_image:"Bild tauschen",
    alt_image:"Alternatives Bild",
    mouseover:"für mouse over",
    mouseout:"für mouse out",
    misc:"Diverses",
    example_img:"Vorschau (Beispiel)",
    missing_alt:"Sind Sie sicher, dass Sie fortsetzen möchten, ohne eine Bildbeschreibung angegeben zu haben? Ohne Beschreibung wird das Bild für Benutzer mit Einschränkungen oder Textbrowser nicht verwendbar.",
    dialog_title:"Bild einfügen/bearbeiten",
    src:"Bild-URL",
    alt:"Bildbeschreibung",
    list:"Bilderliste",
    border:"Begrenzung",
    dimensions:"Abmessungen",
    vspace:"Vertikaler Zwischenraum",
    hspace:"Horizontaler Zwischenraum",
    align:"Ausrichtung",
    align_baseline:"Basislinie",
    align_top:"Oben",
    align_middle:"Mitte",
    align_bottom:"Unten",
    align_texttop:"Textoberkante",
    align_textbottom:"Textunterkante",
    align_left:"Links",
    align_right:"Rechts",
    image_list:"Bilderliste",
    loading:"Lade"
});